server:
  port: 8099
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
      discovery: #服务注册相关配置
        namespace: mic-service
        group: mic-service-project
      config: #配置文件相关配置
        namespace: mic-service
        group: mic-service-project
        file-extension: yaml
        refresh-enabled: true
    gateway:
      routes:
        - id: user-service
#          uri: http://localhost:8091
          uri: lb://:user-service
          predicates:
            - Path=/user/**
        - id: order-service
#          uri: http://localhost:8090
          uri: lb://:order-service
          predicates:
            - Path=/order/**

