server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://192.168.101.65:3306/mic_service_test?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.kyrie.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:sss
