server:
  port: 10010

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service  #http://192.168.101.65:8085/order/
          predicates:
            - Path=/order/**

        - id: user-service
          uri: lb://user-service   #http://192.168.101.65:8084/user/
          predicates:
             - Path=/user/**

